api_platform:

    # The title of the API.
    title: 'DIGITAL-JOBS-API'

    # The version of the API.
    version: '0.2.0'

    # The description of the API.
    description: 'API for the presentation of digital professions'

    # Allow using plain IDs for JSON format.
    allow_plain_identifiers: true

    mapping:
        paths: ['%kernel.project_dir%/src/Entity']

    patch_formats:
        json: ['application/merge-patch+json']

    swagger:
        versions: [3]

    formats:
        json: [ 'application/json' ]
        jsonld: [ 'application/ld+json' ]
        html: [ 'text/html' ]
        multipart: [ 'multipart/form-data' ]
